### ISSUE TITLE
[Migration tooling] Code callouts

### ISSUE THREAD

**Issue by bmorelli25** [elastic/docs-builder#102]
### Summary

Follow-up to #7.

Asciidoctor implementation: https://github.com/elastic/docs?tab=readme-ov-file#callouts
Example: https://www.elastic.co/guide/en/observability/current/apm-open-telemetry-direct.html#apm-connect-open-telemetry-collector

**Comment by Mpdreamz** [comment]
I'm close to implementing this just a note on the syntax


````markdown

```yaml
project:
  title: MyST Markdown 
  github: https://github.com/jupyter-book/mystmd
  license:
    code: MIT
    content: CC-BY-4.0 <1>
  subject: MyST Markdown 
```

1. The license
````

A code block can include `<\d+>` at the end to indicate code callouts. A code block with this style of callouts **needs** to be followed by an ordered list with an equal amount of items as called out. Otherwise the docs-builder will throw an error.


We will also support 'magic' callouts:

````markdown
```csharp
var apiKey = new ApiKey("<API_KEY>"); // Set up the api key
var client = new ElasticsearchClient("<CLOUD_ID>", apiKey); 
```
````

Here nothing needs to be numbered and `// Set up the api key` will be removed from the code block and rendered as the first callout. 

This currently works for comments starting with `//` and `#` which will cover the majority of languages. 


Note the comments have the follow code to be hoisted as a callout.

````markdown
```csharp
// THIS IS NOT A CALLOUT
var apiKey = new ApiKey("<API_KEY>"); // THIS IS
var client = new ElasticsearchClient("<CLOUD_ID>", apiKey); 
```
````

**Comment by bmorelli25** [comment]
This is fantastic! Syntax LGTM. Magic mode will be very nice for short-form callouts.
